# Generated by Django 5.2.17 on 2026-08-31 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_type', models.CharField(choices=[('credit', 'นับหน่วยกิต'), ('audit', 'audit (ไม่นับหน่วยกิต)')], default='credit', max_length=10)),
                ('status', models.CharField(choices=[('enrolled', 'ลงทะเบียนอยู่'), ('withdrawn', 'ถอนแล้ว'), ('completed', 'เรียนจบแล้ว (มีเกรด)')], default='enrolled', max_length=15)),
                ('grade', models.CharField(blank=True, max_length=2, null=True)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Faculties',
            },
        ),
        migrations.CreateModel(
            name='OpenClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_grade', models.CharField(choices=[('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D+', 'D+'), ('D', 'D'), ('F', 'F')], default='D', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Universities',
            },
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curricula', to='registration.department')),
            ],
            options={
                'verbose_name_plural': 'Curricula',
                'unique_together': {('department', 'code')},
            },
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='registration.faculty'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('cash', 'เงินสด'), ('bank_transfer', 'โอนเงิน'), ('credit_card', 'บัตรเครดิต'), ('qr_promptpay', 'พร้อมเพย์')], default='qr_promptpay', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'รอชำระ'), ('paid', 'ชำระแล้ว'), ('failed', 'ชำระไม่สำเร็จ')], default='pending', max_length=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='registration.enrollment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='เช่น ภาคปกติ, ภาคพิเศษ, ภาคนานาชาติ', max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='registration.department')),
            ],
            options={
                'ordering': ['department__code', 'name'],
                'unique_together': {('department', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.CharField(max_length=10)),
                ('instructor_name', models.CharField(max_length=200)),
                ('max_capacity', models.PositiveSmallIntegerField()),
                ('open_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='registration.openclass')),
                ('program', models.ForeignKey(blank=True, help_text='เงื่อนไข #9: ล็อกว่า section นี้เปิดรับเฉพาะภาคไหน (เว้นว่าง = ทุกภาคลงได้)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='registration.program')),
            ],
            options={
                'unique_together': {('open_class', 'section_number')},
            },
        ),
        migrations.CreateModel(
            name='ScheduleSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_type', models.CharField(choices=[('lecture', 'บรรยาย'), ('lab', 'ปฏิบัติการ')], default='lecture', max_length=10)),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'จันทร์'), (1, 'อังคาร'), (2, 'พุธ'), (3, 'พฤหัสบดี'), (4, 'ศุกร์'), (5, 'เสาร์'), (6, 'อาทิตย์')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room', models.CharField(blank=True, max_length=50)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='registration.section')),
            ],
        ),
        migrations.AddField(
            model_name='enrollment',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='registration.section'),
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(help_text='ปีการศึกษา เช่น 2569')),
                ('term', models.PositiveSmallIntegerField(help_text='ภาคเรียน 1/2/3(ฤดูร้อน)')),
                ('registration_start', models.DateTimeField()),
                ('registration_end', models.DateTimeField()),
                ('withdrawal_deadline', models.DateTimeField(help_text='เส้นตายการถอนวิชา (แยกจากช่วงลงทะเบียน)')),
            ],
            options={
                'ordering': ['-year', '-term'],
                'unique_together': {('year', 'term')},
            },
        ),
        migrations.AddField(
            model_name='openclass',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_classes', to='registration.semester'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=15, unique=True)),
                ('year_level', models.PositiveSmallIntegerField(default=1)),
                ('gpa', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('status', models.CharField(choices=[('active', 'ปกติ'), ('probation', 'รอพินิจ'), ('suspended', 'พักการเรียน / ถูกตัดสิทธิ์')], default='active', max_length=20)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='registration.curriculum')),
                ('program', models.ForeignKey(help_text='ภาคของนักศึกษา (ต้องอยู่ในภาควิชาเดียวกับ curriculum.department)', on_delete=django.db.models.deletion.PROTECT, related_name='students', to='registration.program')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='registration.student'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('credits', models.PositiveSmallIntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='registration.department')),
                ('prerequisites', models.ManyToManyField(related_name='unlocks', through='registration.Prerequisite', to='registration.subject')),
            ],
        ),
        migrations.AddField(
            model_name='prerequisite',
            name='required_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_for_links', to='registration.subject'),
        ),
        migrations.AddField(
            model_name='prerequisite',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_links', to='registration.subject'),
        ),
        migrations.AddField(
            model_name='openclass',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_classes', to='registration.subject'),
        ),
        migrations.CreateModel(
            name='CurriculumSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('core', 'Core Subject (วิชาแกน)'), ('major_elective', 'Major Elective (วิชาเลือกสาขา)'), ('gened', 'GenEd (วิชาศึกษาทั่วไป)')], max_length=20)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_subjects', to='registration.curriculum')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_links', to='registration.subject')),
            ],
        ),
        migrations.AddField(
            model_name='faculty',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculties', to='registration.university'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('faculty', 'code')},
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'enrolled')), fields=('student', 'section'), name='unique_active_enrollment_per_section'),
        ),
        migrations.AlterUniqueTogether(
            name='prerequisite',
            unique_together={('subject', 'required_subject')},
        ),
        migrations.AlterUniqueTogether(
            name='openclass',
            unique_together={('subject', 'semester')},
        ),
        migrations.AlterUniqueTogether(
            name='curriculumsubject',
            unique_together={('curriculum', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='faculty',
            unique_together={('university', 'code')},
        ),
    ]
